CREATE TABLE IF NOT EXISTS PUBLIC.ARTISTS (
    ARTISTID VARCHAR(256) NOT NULL,
    NAME VARCHAR(256),
    LOCATION VARCHAR(256),
    LATTITUDE NUMERIC(18, 0),
    LONGITUDE NUMERIC(18, 0)
);

CREATE TABLE IF NOT EXISTS PUBLIC.SONGPLAYS (
    PLAYID VARCHAR(32),
    START_TIME TIMESTAMP,
    USERID INT4,
    LEVEL VARCHAR(256),
    SONGID VARCHAR(256),
    ARTISTID VARCHAR(256),
    SESSIONID INT4,
    LOCATION VARCHAR(256),
    USER_AGENT VARCHAR(256),
    CONSTRAINT SONGPLAYS_PKEY PRIMARY KEY (PLAYID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.SONGS (
    SONGID VARCHAR(256) NOT NULL,
    TITLE VARCHAR(256),
    ARTISTID VARCHAR(256),
    YEAR INT4,
    DURATION NUMERIC(18, 0),
    CONSTRAINT SONGS_PKEY PRIMARY KEY (SONGID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_EVENTS (
    ARTIST VARCHAR(256),
    AUTH VARCHAR(256),
    FIRSTNAME VARCHAR(256),
    GENDER VARCHAR(256),
    ITEMINSESSION INT4,
    LASTNAME VARCHAR(256),
    LENGTH NUMERIC(18, 0),
    LEVEL VARCHAR(256),
    LOCATION VARCHAR(256),
    METHOD VARCHAR(256),
    PAGE VARCHAR(256),
    REGISTRATION NUMERIC(18, 0),
    SESSIONID INT4,
    SONG VARCHAR(256),
    STATUS INT4,
    TS INT8,
    USERAGENT VARCHAR(256),
    USERID INT4
);

CREATE TABLE IF NOT EXISTS PUBLIC.STAGING_SONGS (
    NUM_SONGS INT4,
    ARTIST_ID VARCHAR(256),
    ARTIST_NAME VARCHAR(256),
    ARTIST_LATITUDE NUMERIC(18, 0),
    ARTIST_LONGITUDE NUMERIC(18, 0),
    ARTIST_LOCATION VARCHAR(256),
    SONG_ID VARCHAR(256),
    TITLE VARCHAR(256),
    DURATION NUMERIC(18, 0),
    YEAR INT4
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    USERID INT4 NOT NULL,
    FIRST_NAME VARCHAR(256),
    LAST_NAME VARCHAR(256),
    GENDER VARCHAR(256),
    LEVEL VARCHAR(256),
    CONSTRAINT USERS_PKEY PRIMARY KEY (USERID)
);

CREATE TABLE IF NOT EXISTS TIME (
    START_TIME TIMESTAMP PRIMARY KEY,
    HOUR VARCHAR,
    DAY VARCHAR,
    WEEK VARCHAR,
    MONTH VARCHAR,
    YEAR VARCHAR,
    WEEKDAY VARCHAR
);